# Generated by Django 2.1 on 2018-09-27 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_add', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_basis', models.CharField(max_length=32)),
                ('audit_opinion', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_basis', models.CharField(max_length=32)),
                ('material_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.ProductInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.ProductInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('pass_word', models.CharField(max_length=32)),
                ('user_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.UserType'),
        ),
        migrations.AddField(
            model_name='returnwarehouse',
            name='operator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Return_Warehouse_operator_id', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='returnwarehouse',
            name='use_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_user', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='returnwarehouse',
            name='user_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReturnWarehouse_user_department', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='purchasewarehouse',
            name='operator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_id', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='purchasewarehouse',
            name='wareh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.Warehouse'),
        ),
        migrations.AddField(
            model_name='purchasewarehouse',
            name='warehouse_request_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_request_user', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.ProductType'),
        ),
        migrations.AddField(
            model_name='materialuserequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='materialuserequest',
            name='application_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_department', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='materialuserequest',
            name='material_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.ProductInfo'),
        ),
        migrations.AddField(
            model_name='materialoutrequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_id', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='materialoutrequest',
            name='material_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.ProductInfo'),
        ),
        migrations.AddField(
            model_name='materialoutrequest',
            name='operator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Material_Out_operator_id', to='background_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='materialoutrequest',
            name='use_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_system.Department'),
        ),
    ]
